package com.ciatch.gdp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MedicationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicationAllPropertiesEquals(Medication expected, Medication actual) {
        assertMedicationAutoGeneratedPropertiesEquals(expected, actual);
        assertMedicationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicationAllUpdatablePropertiesEquals(Medication expected, Medication actual) {
        assertMedicationUpdatableFieldsEquals(expected, actual);
        assertMedicationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicationAutoGeneratedPropertiesEquals(Medication expected, Medication actual) {
        assertThat(expected)
            .as("Verify Medication auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicationUpdatableFieldsEquals(Medication expected, Medication actual) {
        assertThat(expected)
            .as("Verify Medication relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicationUpdatableRelationshipsEquals(Medication expected, Medication actual) {
        // empty method
    }
}
