package com.ciatch.gdp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PrescriptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrescriptionAllPropertiesEquals(Prescription expected, Prescription actual) {
        assertPrescriptionAutoGeneratedPropertiesEquals(expected, actual);
        assertPrescriptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrescriptionAllUpdatablePropertiesEquals(Prescription expected, Prescription actual) {
        assertPrescriptionUpdatableFieldsEquals(expected, actual);
        assertPrescriptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrescriptionAutoGeneratedPropertiesEquals(Prescription expected, Prescription actual) {
        assertThat(expected)
            .as("Verify Prescription auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrescriptionUpdatableFieldsEquals(Prescription expected, Prescription actual) {
        assertThat(expected)
            .as("Verify Prescription relevant properties")
            .satisfies(e -> assertThat(e.getPrescriptionDate()).as("check prescriptionDate").isEqualTo(actual.getPrescriptionDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrescriptionUpdatableRelationshipsEquals(Prescription expected, Prescription actual) {
        // empty method
    }
}
