export enum MedicalSpecialty {
  GENERAL_PRACTITIONER = 'GENERAL_PRACTITIONER',

  CARDIOLOGIST = 'CARDIOLOGIST',

  DERMATOLOGIST = 'DERMATOLOGIST',

  PEDIATRICIAN = 'PEDIATRICIAN',

  GYNECOLOGIST = 'GYNECOLOGIST',

  NEUROLOGIST = 'NEUROLOGIST',

  ORTHOPEDIST = 'ORTHOPEDIST',

  DENTIST = 'DENTIST',

  OPHTHALMOLOGIST = 'OPHTHALMOLOGIST',

  PSYCHIATRIST = 'PSYCHIATRIST',

  SURGEON = 'SURGEON',

  OTHER = 'OTHER',
}
